### ISSUE TITLE
npm install error - 'boilerplate intaller'

### ISSUE THREAD

**Issue by Textures** [Rhym/silverstripe-boilerplate-installer#1]
npm install results in....

npm ERR! Invalid name: "boilerplate intaller"

**Comment by Rhym** [comment]
Comment for the closure?

**Comment by Textures** [comment]
HE FIXED IT. IT'S GOOD.

**Comment by Rhym** [comment]
Fixed as of https://github.com/Rhym/silverstripe-boilerplate-installer/commit/f18b96fba3ff0a8c9dd94681949a9a5a6499971f
